"""Email delivery service — Resend (primary) with SMTP fallback."""
import logging
import smtplib
import textwrap
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import resend

from app.config import get_settings

logger = logging.getLogger(__name__)


def _markdown_to_html(md: str) -> str:
    """Very lightweight markdown → HTML converter (no dependencies needed)."""
    lines = md.split("\n")
    html_lines: list[str] = []
    for line in lines:
        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
        elif line.startswith("- ") or line.startswith("* "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.startswith("**") and line.endswith("**"):
            html_lines.append(f"<strong>{line[2:-2]}</strong>")
        elif line.strip() == "---":
            html_lines.append("<hr>")
        elif line.strip() == "":
            html_lines.append("<br>")
        else:
            # Bold inline
            import re
            line = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            html_lines.append(f"<p>{line}</p>")
    return "\n".join(html_lines)


def _build_html(summary: str) -> str:
    body = _markdown_to_html(summary)
    return textwrap.dedent(f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               background:#f5f7fa; margin:0; padding:24px; color:#1a202c; }}
        .card {{ background:#fff; border-radius:12px; padding:32px 40px;
                 max-width:700px; margin:0 auto;
                 box-shadow: 0 4px 24px rgba(0,0,0,0.08); }}
        .header {{ background: linear-gradient(135deg,#6366f1,#8b5cf6);
                   color:#fff; border-radius:8px; padding:20px 28px; margin-bottom:28px; }}
        .header h1 {{ margin:0; font-size:22px; }}
        .header p {{ margin:6px 0 0; opacity:0.85; font-size:14px; }}
        h2 {{ color:#4f46e5; border-bottom:2px solid #e8e8ff; padding-bottom:6px; }}
        h3 {{ color:#6366f1; }}
        li {{ margin-bottom:6px; }}
        strong {{ color:#3730a3; }}
        .footer {{ text-align:center; color:#9ca3af; font-size:12px; margin-top:28px; }}
      </style>
    </head>
    <body>
      <div class="card">
        <div class="header">
          <h1>📊 Sales Executive Summary</h1>
          <p>AI-powered analysis generated by Sales Insight Automator</p>
        </div>
        {body}
        <div class="footer">
          Generated by Sales Insight Automator · Powered by Google Gemini
        </div>
      </div>
    </body>
    </html>
    """).strip()


async def send_email(to_email: str, summary: str) -> bool:
    """Send the executive summary email. Uses Resend if configured, SMTP otherwise."""
    settings = get_settings()
    subject = "📊 Your Sales Executive Summary is Ready"
    html_body = _build_html(summary)

    if settings.use_resend:
        return await _send_via_resend(to_email, subject, html_body, summary, settings)
    else:
        return await _send_via_smtp(to_email, subject, html_body, summary, settings)


async def _send_via_resend(to_email: str, subject: str, html: str, text: str, settings) -> bool:
    """Send via Resend API."""
    resend.api_key = settings.resend_api_key
    try:
        params: resend.Emails.SendParams = {
            "from": settings.email_from,
            "to": [to_email],
            "subject": subject,
            "html": html,
            "text": text,
        }
        email = resend.Emails.send(params)
        logger.info("Email sent via Resend. ID: %s", email.get("id"))
        return True
    except Exception as exc:
        logger.exception("Resend delivery failed: %s", exc)
        raise RuntimeError(f"Email delivery failed: {exc}") from exc


async def _send_via_smtp(to_email: str, subject: str, html: str, text: str, settings) -> bool:
    """Send via SMTP (fallback)."""
    if not settings.smtp_host:
        raise RuntimeError(
            "No email provider configured. Set RESEND_API_KEY or SMTP_HOST in your .env file."
        )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.email_from
    msg["To"] = to_email
    msg.attach(MIMEText(text, "plain"))
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            if settings.smtp_use_tls:
                server.starttls()
            if settings.smtp_username and settings.smtp_password:
                server.login(settings.smtp_username, settings.smtp_password)
            server.sendmail(settings.email_from, [to_email], msg.as_string())
        logger.info("Email sent via SMTP to %s", to_email)
        return True
    except Exception as exc:
        logger.exception("SMTP delivery failed: %s", exc)
        raise RuntimeError(f"SMTP delivery failed: {exc}") from exc
